ideapad/config/routes.rb
Ideapad::Application.routes.draw do
devise_for :users

  resources :ideas
root to:"ideas#index"

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

end

ideapad/app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :description, :title
  belongs_to :user
end

ideapad/app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

ideapad/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :ideas
end

ideapad/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ideapad/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

ideapad/app/helpers/application_helper.rb
module ApplicationHelper
end

ideapad/app/helpers/ideas_helper.rb
module IdeasHelper
end

ideapad/app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ideapad/app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

ideapad/app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<% @ideas.in_groups_of(3) do |group| %>

  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="span4">
        <h4><%= link_to idea.title, idea %></h4>
        <%= idea.description %><br/>
        <em><%= idea.user.try(:email) %></em>
        <p>
          <%= link_to 'Edit', edit_idea_path(idea) %> |
          <%= link_to 'Destroy', idea, confirm: 'Are you sure?', method: :delete %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

ideapad/app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

ideapad/app/views/ideas/show.html.erb
<div class="row">

  <div class="span3">

    <p><b>Name: </b><%= @idea.title %></p>

    <p><b>Description: </b><%= @idea.description %></p>

    <p><b>By: </b><%= @idea.user.try(:email) %></p>
    <p>
      <%= link_to 'Edit', edit_idea_path(@idea) %> |

      <%= link_to 'Destroy', @idea, confirm: 'Are you sure?', method: :delete %> |
      
      <%= link_to 'Back', ideas_path %>
    </p>
  </div>
</div>

ideapad/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideapad</title>
  
  <%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap.min.css", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
      <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
      </p>

      <%= link_to "Ideas", ideas_path, class: "brand" %>

      <ul class="nav">
      <li ><%= link_to 'New Idea', new_idea_path %></li>
      </ul>
      
  </div>
</div>


<% if notice %>
	<p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>